lool
Yandex-Practicum/go-rest-api-homework pull request #182
Opened 2024-09-18 20:36 UTC by naluneotlichno

2024-09-19 16:00 UTC, just-musha requested changes
Привет! Неплохо, ошибки все проверены - супер. Пару комментов рекомендую проверить / поправить, и работа будет принята!

2024-09-19 16:00 UTC, just-musha commented on precode.go
> +	tasks[task.ID] = task
Перед этой операцией полезно добавить проверку - есть ли уже такой ID. И если да - вернуть ошибку пользователю. Иначе задача может быть перезатерта

2024-09-19 16:00 UTC, just-musha commented on precode.go
> +	json.NewEncoder(w).Encode(task)
Это здесь нужно? Стоит проверить как выглядит ответ этой ручки

2024-09-19 16:00 UTC, just-musha commented on precode.go
> +	_, err = w.Write(resp)
Круто что проверяешь ошибки явно

2024-09-19 21:12 UTC, naluneotlichno commented on precode.go
> +	json.NewEncoder(w).Encode(task)
Согласен. Можно было и через Chat GPT проверить. Сразу выдал ошибку. Глаза замылились в процессе написания)

2024-09-19 21:29 UTC, naluneotlichno commented on precode.go
> +	tasks[task.ID] = task
Логично.

2024-09-19 21:33 UTC, naluneotlichno commented on precode.go
> +	_, err = w.Write(resp)
^^

2024-09-19 21:55 UTC, naluneotlichno commented on precode.go
> +	_, err = w.Write(resp)
Класная телега у тебя. кстати. Подписался)

2024-09-20 12:22 UTC, just-musha commented on precode.go
> +	_, err = w.Write(resp)
> Класная телега у тебя. кстати. Подписался)

Рада. Добро пожаловать!

2024-09-20 12:29 UTC, just-musha approved these changes
Супер. Мелочевка осталась. Принято!

2024-09-20 12:29 UTC, just-musha commented on precode.go
> +        http.Error(w, "Задача с таким ID уже существует", http.StatusConflict)
Форматирование съехало, рекомендую добавить `go fmt` в настройки IDE, в автозапуск при сохранении

2024-09-20 12:29 UTC, just-musha commented on precode.go
> +
Пустую строчку можно совсем убрать

2024-09-20 15:18 UTC, naluneotlichno commented on precode.go
> +        http.Error(w, "Задача с таким ID уже существует", http.StatusConflict)
> Форматирование съехало, рекомендую добавить `go fmt` в настройки IDE, в автозапуск при сохранении

Спасибо за фичу. Учту в следующих проектах.

2024-09-20 17:04 UTC, just-musha commented on precode.go
> +	json.NewEncoder(w).Encode(task)
> Согласен. Можно было и через Chat GPT проверить. Сразу выдал ошибку. Глаза замылились в процессе написания)

Потестить через Postman лучше

2025-02-08 16:51 UTC, closed without merging